export  const initialState = {
  localCustom: "",
  loadingTerminal: "",
  dischargeTerminal: "",
  loadingDate: "",
  loadingTime: "",
  arrivalDate: "",
  croIssueDate: "",
  expiryDate: "",
  costCenter:"",
  egm: "",
  etd: "",
  book: "",
  gatePass: "",
  gatePassDate: "",
  letter: "",
  cro: "",
  validityDate: "",
  berth: "",
  viaPort: "",
  containerInfo: "",
  portOfReciept: "",
  portOfReciept: "",
  instruction: "",
  loadingFlag: "",
  status: "",
  allocAvailable: "",
  contAvailable: "",
  sobDate: "",
  containerSplit: "",
  blRequired: "",
  containerWt: "",
  containerTemp: "",
  vent: "",
  loadingTerms: "",
};
